version: "2"
services:
    db:
       image: mysql:5
       container_name: open_course_db
       environment:
          MYSQL_DATABASE: uml_open_course_db
          MYSQL_ROOT_PASSWORD: dgutdev#uml
       volumes:
         - /db:/var/lib/mysql
         - ./db/mysql:/etc/mysql
       restart: always
       ports:
         - "3307:3306"
    web:
        image: open_course
        container_name: open_course_web
        restart: always
        links:
          - db
        ports:
          - "80:8080"
